### ISSUE TITLE
Representation of T&D `SOURCE` elements

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#10]
GB/T 1.1-2009 follows an older version of the ISO Directives Part 2 (2004), and the `[SOURCE: ...]` syntax was not there back then.

This is a real example of usage within GB/T 1.1-2009, the GB Directives.

<img width="751" alt="screen shot 2018-02-14 at 5 36 41 pm" src="https://user-images.githubusercontent.com/11865/36239437-b7535bdc-11ad-11e8-80d0-e0bf4373ab64.png">

So we can do it like this for now.

**Comment by ronaldtse** [comment]
The text is:

```
[GB/T 20000.1--2002, 定义 2.1.4]
```

"定义" means "definition".

We might also want to think about the punctuation and symbol marks that differ in Chinese / ASCII, given the discussion in the RFC list...

If I type this in Simplified Chinese it will be:
```
【GB/T 20000.1--2002，定义 2.1.4】
```

Thoughts?

**Comment by opoudjis** [comment]
I've missed the RFC discussion clearly, though I was reading the other day about the difference between Simplified/Traditional punctuation. There will need to be an audit of punctuation generated by the gem, and localisation where needed.

**Comment by opoudjis** [comment]
Is 定义 "definition", or is it just "section"? Because "section" is not being translated here...

**Comment by opoudjis** [comment]
I have done *something* like this; please review. If 定义 is not "section", we can close the ticket.

**Comment by ronaldtse** [comment]
定义 means "definition"

GB/T 1.1 gives the following definitions:
* Part: 部分 （XXXX.1）(in text: 第1部分）
* Section： 章  5 (in text: 第5章）
* Clause： 条 5.1 , 5.1.1（both same）(in text: 第5.1条）
* Paragraph： 段  [unnumbered]
* List： 列项 （ top level alphabetical a) b), second level numeric 1) 2))
* Annex：附录 A (in text: 附录 A）

**Comment by opoudjis** [comment]
Thank you. A couple more translations pending in #17

**Comment by ronaldtse** [comment]
Updated -- @opoudjis could you please check?

**Comment by opoudjis** [comment]
Sorry, where have you updated what?

**Comment by ronaldtse** [comment]
@opoudjis earlier I updated the message above for better clarity, so whatever you see now should be correct.
