### ISSUE TITLE
Update GbStandardEquivalence to be optional and contain a status + title

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#12]
Equivalence is an optional thing -- e.g. GB standards that did not originate from ISO has no equivalence status.

According to this change:

https://github.com/riboseinc/gbdoc/commit/c9c461101e00b84241ab8ce183227a1e1f60a946

**Comment by opoudjis** [comment]
Is the title the ISO document? If so, shouldn't this be a docRelation instead, and a proper citation? ("Bibliographic Item")

**Comment by opoudjis** [comment]
Equivalence is indeed optional.

**Comment by ronaldtse** [comment]
For GB standards derived from ISO standards, there will be the ISO title:

* presented on the title page
* placed below the Chinese title
* placed within parenthesis

It would seem appropriate to use a docRelation indeed! You are a genius. When I was thinking about it this approach seemed like an overkill, but this indeed make the data much more reusable this way. Let's go for it.

Currently "docRelation" is only for StandardDocument and does not apply to the BibItem. Would it be more appropriate to move "docRelation" to the BibItem itself? And the relationships that "docRelation" can define would be URIs, like `https://isodoc.org/doc-relations/equivalent` and `https://isodoc.org/doc-relations/supercedes`?

Do you think the "Citation" model may not be so appropriate here since we're not creating a textual citation, but a direct docReference?

**Comment by opoudjis** [comment]
I'd rather keep the doc relation in the standard: I'm not sure it is static the way bibliographic references are. The relations can be just enums, we don't have a linked data use case.

**Comment by opoudjis** [comment]
The related document will end up in the bibliography anyway (if not in not this case, certainly in the general case), and I think it would be confusing to mention it as a BibItem in two places.

**Comment by opoudjis** [comment]
No, I've changed my mind. It will be a full bibitem. Any references in The bibliography are autonomous from where this reference will be used.

**Comment by ronaldtse** [comment]
If DocRelation lives in the BibliographicItem model, it can serve useful for the case of a bibliographic graph (i.e., without the actual document content).

For example in the case of a GB standard, these two things can happen at once. This is a real example.
* this document obsoletes another document (GB/T 22080-2016 obsoletes GB/T22080-2008)
* this document is derived from another document (GB/T 22080-2016 is identical to ISO/IEC 27001:2013)

Then in the GB standard front page, it shows this in 2 ways:

1. Inclusion in the full document identifier: "GB/T 22080-2016/ISO/IEC 27001:2013".
  * But the short reference is still "GB/T 22080-2016". In this example, the document shows it obsoletes "GB/T 22080-2008" but does not mention the full "GB/T 22080-2008/ISO/IEC 27001:2005".
  * Inclusion into the full document identifier is only used when the relation to the international standard is "IDT" (identical).

2. On the front page, below the English title, there is the title of the source document provided within parenthesis like this `( {{ docrelations.source.shortref }}, {{ docrelations.source.gb-relation-code }} )`

<img width="634" alt="screen shot 2018-02-18 at 12 02 56 pm" src="https://user-images.githubusercontent.com/11865/36347789-b41176fe-14a3-11e8-8251-3fe2b3e2a829.png">

**Comment by opoudjis** [comment]
So: bibdata/docrelations/{equivalent|nonequivalent|identical} with a bibitem citation.

**Comment by opoudjis** [comment]
@ronaldtse, Need Chinese for "Obsoletes" above.

**Comment by ronaldtse** [comment]
"Obsoletes #{shortref}": “代替 #{shortref}”

**Comment by ronaldtse** [comment]
BTW, in ISO Directives / GB/T 1.1 there is this notion of "replacing a part or the whole of another document." In ISO language it often states that "this standard cancels another document".

Do we model this with a doc-relation with a citation?

**Comment by opoudjis** [comment]
n/m, found it in the HTML template. I see you have a "partly-supersedes" there as well. If you want that as a doc relation, we will need to add it to the vocabulary.

**Comment by ronaldtse** [comment]
We should allow this possibility, but should we:
* have a doc relation that is "partially supersedes"; or
* have a doc relation that is supersedes but qualify locality to the part that it supercedes
?

**Comment by opoudjis** [comment]
hang on, didn't see your response.

We do model obsoleting with a doc relation; my question is whether we model partial obsoleting with another relation. I think we need to.

**Comment by opoudjis** [comment]
Qualifying locality: ... overkill.

**Comment by ronaldtse** [comment]
Qualifying locality => doc relation that acts on a bibitem with a bib-locality.

**Comment by opoudjis** [comment]
I think it's overkill, but I will do it. For GB, if it detects a locality, it will replace "supersedes" with "partly supersedes", but will not name the locality involved.

With the modelling of doc relation, I'd rather we keep it clean as just a bibitem, which can contain a URI, rather than having a bibitem/uri choice.

**Comment by opoudjis** [comment]
@ronaldtse, To confirm: Identical is IDT, not IDN?

**Comment by ronaldtse** [comment]
Yes, from GB/T 20000.2-2009, Guidelines on adoption of international standards.

<img width="1145" alt="screen shot 2018-02-22 at 11 42 23 am" src="https://user-images.githubusercontent.com/11865/36517484-8e3e64a8-17c5-11e8-92b1-984083047213.png">

**Comment by ronaldtse** [comment]
> I think it's overkill, but I will do it. For GB, if it detects a locality, it will replace "supersedes" with "partly supersedes", but will not name the locality involved.

👍
