### ISSUE TITLE
Compilation fails when missing mandatory attributes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#13]
Right now if I miss `:standard-class:` it says:

```
TypeError: no implicit conversion of nil into String
  /Users/user1/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/asciidoctor-gb-07a3606bf240/lib/asciidoctor/gb/metadata.rb:130:in `gsub'
```

Which is quite ugly. It should really provide an error with a hint to the user what needs to be filled in?

**Comment by opoudjis** [comment]
I've got a ticket to validate prefixes; I will make the document default to GB national, but I will issue a warning if it does.
