### ISSUE TITLE
Publisher of national standards GB, GB/T, GB/Z are identical

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#14]
There are only 1 class of national GB standards but three different types:
* GB: Mandatory
* GB/T: Recommended
* GB/Z: Guidelines

Hence the publisher for all of them is identical, namely the `admin` field here:

```ruby
GB: { name: "中华人民共和国国家标准", admin: "中华人民共和国国家质量监督检验检疫总局，中国国家标准化管理委员会"},
```

Note that there are two "admins": "中华人民共和国国家质量监督检验检疫总局" and "中国国家标准化管理委员会"; maybe an array is more appropriate.

Rendered into 2 lines since it is joint publishing:
![footer](https://user-images.githubusercontent.com/11865/36254944-244624a2-11f1-11e8-95c5-288d57b0b838.png)

These two lines in `agencies.rb` for `admin` are really not necessary?

```ruby
"GB/T": { name: "中华人民共和国国家标准", admin: "国家质量监督检验检疫总局"},
"GB/Z": { name: "中华人民共和国国家标准化指导性技术文件", admin: "中华人民共和国国家质量监督检验检疫总局"},
```

In addition, "GB/T" and "GB" both use the same name, the special one is "GB/Z".

**Comment by ronaldtse** [comment]
The font used in the publisher is "Song" (or "Sun") or "Song Ti" (the style of "Song"), which is kind of the serif style. We just need to slightly stretch it taller and narrower and put in a table style.

The "发布" words on the right means "Published"; so this footer means it is published by these two authorities together. In some older standards they put “联合发布” which means "Jointly Published".

**Comment by opoudjis** [comment]
Done. The styling of these in Word HTML is horrendous, because the CSS inheritance implementation is flaky, and the positioning of elements in the given template mixes points and centimeters.
