### ISSUE TITLE
Improve font of Word template

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-gb#15]
@ronaldtse, the first document you sent me had SimSun as its font: https://docs.microsoft.com/el-gr/typography/font-list/simsun-extb . Should I try to apply that throughout the document? On my machine, it's coming up with bad mixtures of fonts.

**Comment by ronaldtse** [comment]
Just uploaded gbdoc/reference-docs/ with a sample Word document ("GBT 22240-20xx CD.doc").

There are basically only two styles in the entire document:
* SimHei (sans-serif)
* SimSun (serif)
