### ISSUE TITLE
Translations pending

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-gb#17]
Have the following that need to be translated into Chinese. If there isn't a simple equivalent, well, we'll deal with that.

* Key (for figures)
* Where (for formulae)
* DEPRECATED (for terms)
* section, clause, paragraph, chapter, page, whole, part (for localities)
* Terms, Definitions, Symbols and Abbreviations

**Comment by opoudjis** [comment]
Part: 部分 （XXXX.1）(in text: 第1部分）
Section： 章 5 (in text: 第5章）
Clause： 条 5.1 , 5.1.1（both same）(in text: 第5.1条）
Paragraph： 段 [unnumbered]
List： 列项 （ top level alphabetical a) b), second level numeric 1) 2))
Annex：附录 A (in text: 附录 A）

**Comment by opoudjis** [comment]
Need "key", where the definitions of symbols & abbreviations used in figures and tables is given. If 式中 works, that's ok by me.

**Comment by ronaldtse** [comment]
Can you give an example usage/screenshot of "Key"?

Example: “例”

```
[example]
Foreign seeds, husks.

[example]
Bran, sand, dust. 
```

=>
```
Example 1: Foreign seeds, husks.
Example 2: Bran, sand, dust. 
```

=>
```
例 1：Foreign seeds, husks.
例 2：Bran, sand, dust. 
```

**Comment by ronaldtse** [comment]
"Key:" in a figure is “说明：”
