### ISSUE TITLE
"Bibliography" section should be placed after all annexes and should not be numbered

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#21]
As title.

See this for example: https://www.tc260.org.cn/file/2018-01-19/451c8608-b7b4-4bf8-84e2-50f325d6b864.doc

**Comment by opoudjis** [comment]
Which is identical to ISO; if GB isn't doing that, it's a bug.

**Comment by ronaldtse** [comment]
Indeed -- but the current way asciidoctor-gb generates the bibliography is numbered.

**Comment by opoudjis** [comment]
I cannot replicate with current code and vuln-GB repo; could you check with bundle update?

**Comment by ronaldtse** [comment]
Oh yes it's fixed! We just need to "center" the "Bibliography" title...

Ours:
<img width="235" alt="screen shot 2018-02-19 at 3 42 43 pm" src="https://user-images.githubusercontent.com/11865/36365168-93d33556-158b-11e8-91b8-b6690c9693ca.png">


Original:
<img width="514" alt="screen shot 2018-02-19 at 3 42 51 pm" src="https://user-images.githubusercontent.com/11865/36365166-9380b722-158b-11e8-8e5d-78a89bbd48a8.png">

**Comment by opoudjis** [comment]
Just done in #24
