### ISSUE TITLE
Getting `ISO Warning` on Bibliography

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#22]
`ISO style: Final section must be (references) Bibliography`

Currently I have this:

```
[bibliography]
== 参考文献

```

**Comment by opoudjis** [comment]
May not be creating the section if it is empty. Will check; what document? GB-Vulnerability?

**Comment by ronaldtse** [comment]
Yes indeed, all pushed.

**Comment by opoudjis** [comment]
Not getting warning now, though the section remains empty. Must have fixed this morning.
