### ISSUE TITLE
External references/No terms on Terms & Definitions

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#23]
This issue mirrors https://github.com/riboseinc/asciidoctor-iso/issues/82.

The boilerplate content is:

```
<<ISO27000, ISO/IEC 27000>> 中确立的以及下列术语和定义适用于本标准。
```

```
<<ISO27000, ISO/IEC 27000>>，<<ISO27001, ISO/IEC 27001>> 和 <<ISO27002, ISO/IEC 27002>> 中确立的以及下列术语和定义适用于本标准。
```

**Comment by opoudjis** [comment]
To do this, I need all of:

* No terms and definitions are listed in this document.
* For the purposes of this document,
* the following terms and definitions apply.
* the terms and definitions given in #{src["citeas"]} apply.
* the terms and definitions given in and the following apply.

**Comment by opoudjis** [comment]
I assume GB has no counterpart of:

````
 <p>ISO and IEC maintain terminological databases for use in 
      standardization at the following addresses:</p>
      <ul> <li> <p>ISO Online browsing platform: available at 
           <link target="http://www.iso.org/obp"/></p> </li>
           <li> <p>IEC Electropedia: available at 
           <link target="http://www.electropedia.org"/></p> </li> </ul>
````

**Comment by ronaldtse** [comment]
* No terms and definitions are listed in this document.
** 本文件不提供术语和定义。（GB/T 1.1-2009 was written before the mandatory nature of the T&D section, so does not provide this. I did the translation instead.)

* When T&D is only given in this document:
** "For the purposes of this document, the following terms and definitions apply."
** 下列术语和定义适用于本文件。 (As defined by GB/T 1.1-2009 6.3.2)

* When using additional sources:
** "For the purposes of this document, the terms and definitions given in #{src["citeas"]} and the following apply."
** #{src["citeas"]} 界定的以及下列术语和定义适用于本文件。(As defined by GB/T 1.1-2009 6.3.2)

* When using external sources:
** "For the purposes of this document, the terms and definitions given in #{src["citeas"]} apply."
** #{src["citeas"]} 界定的术语和定义适用于本文件。(As defined by GB/T 1.1-2009 6.3.2)

Sometimes, they add this line:
** For the convenience of use, the following terms and definitions from #{docname} are given below.
** 为了便于使用，以下重复列出了 #{docname} 中某些术语和定义。

Plurality of citeas:
** "#{docname1}, #{docname2} and #{docname3}"
** "#{docname1}、 #{docname2} 和 #{docname3}"

**Comment by ronaldtse** [comment]
No counterpart of "ISO and IEC maintain terminological databases..." in GB.

**Comment by opoudjis** [comment]
I was hoping to avoid multiple doc sources, but OK, I'll put them in.

**Comment by opoudjis** [comment]
So "为了便于使用，以下重复列出了 #{docname} 中某些术语和定义。" is really a variant of "#{src["citeas"]} 界定的术语和定义适用于本文件。" I'll use the latter.

**Comment by opoudjis** [comment]
Implemented multiple doc sources for isodoc as well.

**Comment by ronaldtse** [comment]
The latter is the typical line. The former is an occurrence within GB/T 1.1, where some definitions are cited AND repeated for ease of use. I don’t know how common this usage is. So if we can allow the author to manually put in an additional sentence after the boilerplate, we cover both cases.

**Comment by opoudjis** [comment]
... Well, currently we don't: I've just started stripping all non-term content in the terms section, so that the correct boilerplate overrules anything the source document has. I'd rather avoid this kind of flexibility, but I can disable stripping boilerplate text out if you want; there's less boilerplate in GB anyway.

**Comment by opoudjis** [comment]
Disabled termdef_boilerplate_cleanup() in asciidoctor-gb

**Comment by ronaldtse** [comment]
Can there be a document attribute that is like ":terms-definitions-disable-boilerplate-enforcement:" ?

**Comment by opoudjis** [comment]
Overkill. All it does is strip extraneous content. If you have the presence of mind to populate `:terms-definitions-disable-boilerplate-enforcement:`, you have the presence of mind to exclude the extraneous content to begin with.
