### ISSUE TITLE
`:iso-standard:` and `:equivalence:` should be optional

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#27]
These two attributes should be optional since a Chinese standard does not always link to an ISO one; e.g., https://github.com/riboseinc/gmt-0009-2012 .

**Comment by opoudjis** [comment]
They are optional in the grammar, because docrelations is optional; and I have just generated a rice document with no mention of either, and with no warnings or mention of ISO on the front page. What behaviour are you seeing?

**Comment by ronaldtse** [comment]
I got confused since the README didn’t say they were optional. Could we mark it there? Thanks!

**Comment by opoudjis** [comment]
Done.
