### ISSUE TITLE
Indenting just like GB drafts

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#34]
The formatting produced is nearly perfect -- baring some indenting differences:

1. Index:
  a. Foreword and Introduction (the unnumbered sections) should have page numbers in upper roman like "II" "III", and should be aligned 
  b. subsections in the index are indented
2. Subsections are indented, subsection text is further indented
3. Document margins are Top/Bottom 1", Left/Right 1.25"
4. Header/footer margin: Header (0.59") Footer (0.69")
5. Empty page between Foreword / Introduction should be removed.
6. Document Title after Introduction should be SimHei 16 without bolding.
7. Terms and Definitions `dl` should separate term and definition with tabs vs (currently) using vertical space + tabs.
8. `[source]` blocks should not be rendered as Examples but as verbatim text
9. Normal text and title text should have some more vertical space to them
  * Subsection: "Header 1 + Before 7.8pt + After 7.8pt
10. etc -- can we actually port the GB Draft Doc Word styles into our GB Docs?

**Comment by opoudjis** [comment]
The `dl` issue also applies to ISO standards, and I was hoping you wouldn't notice :-) . They are rendered as tables in ISO; I hope I don't have to resort to that

**Comment by opoudjis** [comment]
1. The source document had only odd numbered headers and footers, which is odd; I will add even numbered headers and footers.

**Comment by opoudjis** [comment]
5. Done.
6. Done.

**Comment by ronaldtse** [comment]
Is there a way we can directly adopt the GB Word formatting styles -- I see that our current styling is adopted from ISO Word?

e.g., https://www.tc260.org.cn/file/2018-01-19/62f429ed-d80f-4162-a529-68b3a4b34439.doc

**Comment by opoudjis** [comment]
Yes.

**Comment by opoudjis** [comment]
4. Done.

**Comment by opoudjis** [comment]
1a, b: Done.

**Comment by opoudjis** [comment]
2. @ronaldtse, cannot confirm: Subsections in the document you sent are indented the same as clauses; e.g. the text of clause 5 is indented the same as the text of clause 6.1.1

**Comment by opoudjis** [comment]
9. Both the current CSS and the document you sent have single spacing and 0.75 first line indent for normal text. But headers do have more space before and after: changed.

9a. As far as I can tell, it's the same amount of space before and after for all levels of header.

**Comment by opoudjis** [comment]
10. You'd think so, but Word randomises style names, and the CSS of Word is highly idiosyncratic; it's very time consuming to work out what is going on at all.

**Comment by opoudjis** [comment]
8. I will not force sourcecode to be contained within an example for asciidoctor-iso either.

**Comment by opoudjis** [comment]
7 Converted dl for Word output to tables — something long overdue.

**Comment by opoudjis** [comment]
With the exception of 2, which I believe is inaccurate, all actioned.
