### ISSUE TITLE
Using asciidoctor-gb to re-create a GM/T standard

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#38]
This repo (https://github.com/riboseinc/gmt-0009-2012) includes the Chinese original and the English translated version of GM/T 0009-2012, which we want to re-create in GbDoc.

I've made all the changes I thought necessary, but it's still not compiling. The specific error I'm getting (other than the IsoDoc validation that doesn't quite apply) is:
```
NoMethodError: undefined method `children' for nil:NilClass
  /Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/isodoc-8f72fd147e13/lib/isodoc/references.rb:69:in `block in noniso_bibitem'
```

@opoudjis would you be able to help update the repo to make both Chinese + English documents work?

Thanks!

**Comment by ronaldtse** [comment]
Note that in the documents, the Chinese one is `(language: zh, script: Hans)` while the English translation is `(language: en, script: Latn)`.

This sector standard is also a bit funny that there is no authoring TC, the author and manager are both the State Cryptography Administration.

**Comment by opoudjis** [comment]
All good: it was barfing because it was expecting to see a formatted reference in the bibliography, and the bibliography was empty. Fixed.
