### ISSUE TITLE
HTML output should show proper GB content

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#39]
Currently the output is ISO output. We need to migrate this to generate real GB HTML output.

**Comment by opoudjis** [comment]
... More information?

**Comment by ronaldtse** [comment]
A reproduction of the GB cover page, GB Logo, etc?

**Comment by opoudjis** [comment]
Oh, ok. Sure. Is there a precedent for authoritative GB HTML output, or are we just making it up, as a vertically compressed version of the Word title page?

**Comment by ronaldtse** [comment]
I have just confirmed that there is no authoritative GB HTML output. We could however base the formatting on the GB Doc output?
