### ISSUE TITLE
Differential font depending on script

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-gb#41]
All CSS currently uses SimSun/SimHei. If language of spec is Chinese, need to switch font to Times.

**Comment by ronaldtse** [comment]
Maybe there should be a “font profile” for languages and scripts per standard. Users should be able to customize this.

**Comment by opoudjis** [comment]
Depends on https://github.com/riboseinc/isodoc/issues/6 . Once we've templated css, we can feed in config params.

**Comment by opoudjis** [comment]
Done. Config parameters for fonts documented in asciidoctor-iso README. header-font, body-font, monospace-font.
