### ISSUE TITLE
Normative references section not showing references in GM/T 0009

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#45]
In the GM/T 0009 document (https://github.com/riboseinc/gmt-0009-2012/), both Chinese and English, is not showing the full references.

Right now the display is broken in Word and HTML output, like this:

```
2.	规范性引用文件
下列文件对于本文件的应用是必不可少的。 凡是注日期的引用文件，仅注日期的版本适用于本文件。 凡是不注日期的引用文件，其最新版本（包括所有的修改单）适用于本文件。
GM/T 0003, 
GM/T 0004, 
```

```
2.	Normative References
The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.
GM/T 0003, 
GM/T 0004, 
``

Notice that the given title is missing.

**Comment by opoudjis** [comment]
The XML knows that these are ISO-equivalent references; but isodoc does not. Isodoc was assuming that all non-ISO references have formattedref not title, and these had title, so it output nothing. Fixed: if there is title, that will be output instead. (There is a pending ticket to create a new bibliography reference based on ISO 690.)

Moreover, the format for "all parts" was not right, and when I fixed it, it revealed a bug in detection of "all parts" without a year. Fixed.
