### ISSUE TITLE
Problems when using English version (`:script: en`) of a GB standard

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#50]
Problem 1.

"Introduction" is given as the 5th section when English is used. I presume it is because "== 引言" was expected. Is it possible to allow a localization file to take care of this?

Problem 2.

There's a lot of Chinese still on the cover page (and the "Index" title). Can we provide a separate YAML file for pairwise translations?
<img width="704" alt="screen shot 2018-03-29 at 8 59 06 am" src="https://user-images.githubusercontent.com/11865/38062600-caf578a2-332f-11e8-9864-ffdfe5097dc7.png">

**Comment by opoudjis** [comment]
Basically this means English version of the front page templates, which can be done through YAML files. I'd make them additional YAML files.

**Comment by ronaldtse** [comment]
Agree, thanks @opoudjis !

**Comment by opoudjis** [comment]
Front page in English version is now in English, apart from standard class and issuer.

**Comment by opoudjis** [comment]
DOne those too.

**Comment by ronaldtse** [comment]
Wow, it's working! 👍
