### ISSUE TITLE
Allow entering contribution information directly

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#51]
While we have mapping of standard prefixes (e.g., GB) to a "issuer", it may be better if we allow direct entry as there are (officially) so many contribution roles as described here: https://github.com/riboseinc/gbdoc/issues/6 .

* Issuers 发布部门：中华人民共和国国家质量监督检验检疫总局, 中国国家标准化管理委员会
* Proposer 提出单位：新闻出版总置条码中心
* TechnicalCommittees 归口单位：全国信息与文献标准化技术委员会
* Governor 主管部门：国家标准化管理委员会
* DraftingCommittee 起草单位：新闻出版总置条码中心
* DraftingAuthors 起草人：齐相潼、蔡京生、邢瑞华、傅祚华、孔德龙
* Publisher 出版社：中国标准出版社

Can we have a document attribute for each of these?

**Comment by opoudjis** [comment]
Done for Proposer, Governor (as Authority), Publisher.

Issuer is redundant with prefix, and I don't think it should be added.

Technical committees are already there.

Drafting Committee and Drafting Author are just personal and organisational authors, but right now we don't parse authors in the header. Will add.

**Comment by opoudjis** [comment]
I'm putting the issuer into the copyright owner org.
