### ISSUE TITLE
Implement GB document stages

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#52]
GbDoc inherits the same ISO Harmonized stages (with identical meanings and codes) and is harmonized with WTO stages. This is according to GB/T 16733-1997.

Here are the corresponding codes (_CONFIRMED_): (the code names/abbreviations diverge from ISO, but code numbers are identical)

* 00 新工作项目建议 (PWI Preliminary Work Item)
* 10 新工作项目 (NP New work item Proposal)
* 20  标准草案征求意见稿 (WD Working Draft(s))
* 30  标准草案送审稿 (CD Committee Draft(s))
* 40  标准草案报批稿 (DS Draft Standard)
* 50  标准出版稿 (FDS Final Draft Standard)
* 60  国家标准 (National Standard)

Iterations: 
* "{n}次{stagename}" ("二" is number "2", "次" means "times", so the second Committee Draft is "二次征求意见稿")

The cover page changes per stage look like this. The images should actually reflect the official names provided above.

New work item Proposal.

<img width="814" alt="screen shot 2018-03-29 at 2 01 58 pm" src="https://user-images.githubusercontent.com/11865/38071005-cbf74616-3359-11e8-8d96-6c02d31d5a62.png">

Working Draft.
<img width="809" alt="screen shot 2018-03-29 at 1 39 08 pm" src="https://user-images.githubusercontent.com/11865/38071096-665800ba-335a-11e8-90a0-c8c1aa16c97d.png">

This additional text is "在提交反馈意见时，请将您知道的相关专利连同支持文件一并附上". This means "When providing comments, please attach known relevant patent information and supporting documents".

Committee Draft.
<img width="797" alt="screen shot 2018-03-29 at 1 39 36 pm" src="https://user-images.githubusercontent.com/11865/38071102-6c3dd234-335a-11e8-9d94-5be36f4d93bf.png">

Draft Standard.
<img width="805" alt="screen shot 2018-03-29 at 1 39 48 pm" src="https://user-images.githubusercontent.com/11865/38071108-7106e918-335a-11e8-8b54-b5c4aaa40570.png">

**Comment by ronaldtse** [comment]
Updated and stages confirmed.

**Comment by opoudjis** [comment]
This is not explicit enough:

* Do Draft, Draft Standard For Comments, Draft Standard For Examination, Draft Standard for Approval correspond to WD, CD, DS, FDS?
* I need the bracketed text for each stage.

**Comment by opoudjis** [comment]
I am acting as if Draft, Draft Standard For Comments, Draft Standard For Examination, Draft Standard for Approval correspond to WD, CD, DS, FDS, and putting those stage names in the brackets

**Comment by ronaldtse** [comment]
Official English and Chinese names:

00 新工作项目建议 (PWI Preliminary Work Item)
10 新工作项目 (NP New work item Proposal)
20 标准草案征求意见稿 (WD Working Draft(s))
30 标准草案送审稿 (CD Committee Draft(s))
40 标准草案报批稿 (DS Draft Standard)
50 标准出版稿 (FDS Final Draft Standard)
60 国家标准 (National Standard)

**Comment by ronaldtse** [comment]
You can basically ignore the names with the images.

**Comment by opoudjis** [comment]
In that case, this is done. The styling may be wrong, but you are dealing with that anyway.

**Comment by opoudjis** [comment]
... Almost done. Are these codes incorporated into the document identifier, like the ISO abbreviations are?

**Comment by ronaldtse** [comment]
I don't have a definitive answer, but let's treat that as a yes for now.

**Comment by ronaldtse** [comment]
(yes, the latest description overrides what there is in the images)

**Comment by ronaldtse** [comment]
(I've updated the original post to reflect the correct names)

**Comment by opoudjis** [comment]
One last thing: at the moment, the iteration is given as the Arabic numeral. This has to be translated to the Chinese numeral, right?

**Comment by ronaldtse** [comment]
Yes, you're right.

**Comment by ronaldtse** [comment]
You can use this for localizing numerals: https://github.com/twitter/twitter-cldr-rb if it's not too heavy duty.

**Comment by opoudjis** [comment]
Example of this run with CD stage and iteration 3 attached.

[rice.gb.zip](https://github.com/riboseinc/asciidoctor-gb/files/1865505/rice.gb.zip)

**Comment by ronaldtse** [comment]
@opoudjis thanks. I have a new idea -- can we host this GB Doc in a new repo, and we can have separate Chinese and English versions (and separate localization YAMLs), that we can use to test?

**Comment by opoudjis** [comment]
Why should these not simply go to spec/examples for the asciidoctor-iso and asciidoctor-gb repositories? There are in fact rice documents already there for both. And proliferating gems and repositories simply makes this unnavigable for any outsider, and painful to manage.

**Comment by ronaldtse** [comment]
I'd like to separate the purposes, the ones in `spec/examples` are for specs, but the document themselves can be used just like `rfc-asciirfc-template` -- as example documents where people start a document from.

That said, you're right that we should have these in specs to spec against.
