### ISSUE TITLE
Grammar errors

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-gb#53]
With recent grammar changes, large number of errors being reported

**Comment by opoudjis** [comment]
@ronaldtse , way back we decided not to strip out the boilerplate supplied by users for Terms sections in Chinese GB documents. I assume that's still valid?

**Comment by ronaldtse** [comment]
Thoughts @opoudjis ?

**Comment by opoudjis** [comment]
More options is more things that can go wrong, but this makes sense. I'll open a new issue.
