### ISSUE TITLE
GB/T 1.1 requirements on measurements

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#58]
GB/T 1.1 measurements in mm, as specified in I.1 to I.12.

(https://github.com/riboseinc/asciidoctor-gb/issues/47#issuecomment-377791029)

<img width="486" alt="i 1" src="https://user-images.githubusercontent.com/11865/38174233-4d4cb73e-3605-11e8-800c-94798ecdd544.png">

a. CCS code.
b. the issuer of the specific national standard.

<img width="473" alt="i 2" src="https://user-images.githubusercontent.com/11865/38174234-4d8aa4a4-3605-11e8-9379-6e3aeb668734.png">

a. CCS code.
b. the issuer of the specific sector standard.

<img width="469" alt="i 3" src="https://user-images.githubusercontent.com/11865/38174235-4dc58d80-3605-11e8-872f-9650f13d43b5.png">

a. CCS code.
b. the issuer of the specific local standard.

<img width="484" alt="i 4" src="https://user-images.githubusercontent.com/11865/38174236-4e029838-3605-11e8-9ade-30760bcdbee7.png">

Note: this is an odd page purely for example purposes.

<img width="467" alt="i 5" src="https://user-images.githubusercontent.com/11865/38174237-4e40467e-3605-11e8-9765-867ee3bbf379.png">

Note: this is an odd page purely for example purposes.
Note: layout measurements for "Introduction" is identical to "Foreword".

<img width="465" alt="i 6" src="https://user-images.githubusercontent.com/11865/38174238-4e7b2ac8-3605-11e8-826e-1a211cf7b914.png">

<img width="458" alt="i 7" src="https://user-images.githubusercontent.com/11865/38174239-4eb8b23a-3605-11e8-8387-d2162eca4449.png">

Note: this is an odd page purely for example purposes.

<img width="472" alt="i 8" src="https://user-images.githubusercontent.com/11865/38174240-4f14abe4-3605-11e8-8b21-ca4cf43e2862.png">

Note: this is an odd page purely for example purposes.

<img width="466" alt="i 9" src="https://user-images.githubusercontent.com/11865/38174241-4f50c5fc-3605-11e8-8892-9c484b82a6cb.png">

Note: in this example the last element of the content is the glossary, and this is an odd page purely for example purposes.

<img width="459" alt="i 10" src="https://user-images.githubusercontent.com/11865/38174242-4f8c9bea-3605-11e8-884a-00f7f463bf36.png">

<img width="477" alt="i 11" src="https://user-images.githubusercontent.com/11865/38174243-4fc76aae-3605-11e8-8027-5e7e546ac5d3.png">

<img width="458" alt="i 12" src="https://user-images.githubusercontent.com/11865/38174244-5003d002-3605-11e8-83bd-5bb354c0e97f.png">

**Comment by opoudjis** [comment]
Have carried stylesheet and coverpage across from GB/T 19488.2-2008, and have translated point measurements to cm.

**Comment by opoudjis** [comment]
The number after DB is not going to be the same size as the logo gif. *Please* do not ask me to fix it; I've done what I can.

**Comment by ronaldtse** [comment]
Got it. Instead, can we have a document attribute to allow overriding the logo image, in case some DB standards want to use their own image. Thanks!

**Comment by opoudjis** [comment]
Incredibly, Word does not allow space before a paragraph if it follows a page break. (It does allow it after a section break.) https://answers.microsoft.com/en-us/office/forum/office_2013_release-word/style-using-page-break-before-and-spacing-before/56932b98-97e3-495e-bc24-51489649ec97

Workaround for the GB headers which do need space before them on a new page is to make the headers into frames. Yuck.

**Comment by opoudjis** [comment]
Line spacing eats into frame dimensions of header; have to shave 0.3cm bottom and top

**Comment by ronaldtse** [comment]
@opoudjis isn't the simple way for an indent before a paragraph is to make an indent two spaces wide?

**Comment by opoudjis** [comment]
Like I said: Word ignores any spacing after a page break.

**Comment by opoudjis** [comment]
.... That's horizontal space. I'm talking about vertical space.

**Comment by ronaldtse** [comment]
Aha, got it.
