### ISSUE TITLE
Displayed document identifier should use English abbreviation

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#61]
The "red" text should write "GB/T CD3 17301.1" instead of "GB/T 三次标准草案送审稿 17301-1".

(Also, on the cover page, the font used for number "17301.1" should be SimHei, "dash" should be the Chinese dash, see below)
<img width="227" alt="screen shot 2018-04-03 at 8 49 26 am" src="https://user-images.githubusercontent.com/11865/38221723-f05600d6-371b-11e8-856a-367e1e9df64f.png">

Cover page:
<img width="840" alt="screen shot 2018-04-03 at 8 22 52 am" src="https://user-images.githubusercontent.com/11865/38221432-778f6d14-371a-11e8-87fd-6d9e1c6f6b83.png">

Page headers:
<img width="442" alt="screen shot 2018-04-03 at 8 41 07 am" src="https://user-images.githubusercontent.com/11865/38221507-ccaeb250-371a-11e8-9cd2-32980cb7e570.png">

**Comment by opoudjis** [comment]
In Chinese and English documents, or only English documents?

**Comment by opoudjis** [comment]
Which means then that the Chinese text for stages appears nowhere in the document, right?

(Which means it was correct before. :-( )

**Comment by ronaldtse** [comment]
@opoudjis let me clarify:

1. The full stage name should appear in the middle of the cover page
2. The document identifier should include the stage initials as defined in https://github.com/riboseinc/asciidoctor-gb/issues/60 (e.g., PWI, NP, WDx, CDx, DISx, FDISx)

**Comment by opoudjis** [comment]
OK, got it
