### ISSUE TITLE
Cover page styling: standard title and equivalence

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#64]
1. The "emdash" between the title parts in both Chinese and English are uneven (see "red"). 
2. The part for equivalence: no space needed between "ISO 1231" and ",", no space needed between "," and "MOD") (no space is needed after a Chinese comma -- maybe this should be a general "script=zh" concern)
3. In GB/T 1.1 the "Part" title part does not come with an emdash, but a space is used to separate. See further below.
4. The "Part" section of "第1部: " should be "第1部分：" (again, no whitespace after Chinese colon)

Current:
<img width="828" alt="screen shot 2018-04-03 at 9 08 51 am" src="https://user-images.githubusercontent.com/11865/38222354-2e7648a0-371f-11e8-9725-f46e6ab6a6d1.png">

Original:
<img width="836" alt="screen shot 2018-04-03 at 9 10 09 am" src="https://user-images.githubusercontent.com/11865/38222357-329c120c-371f-11e8-90cf-56029aaccce3.png">

Other examples of title part "Part":
<img width="366" alt="screen shot 2018-04-03 at 9 13 46 am" src="https://user-images.githubusercontent.com/11865/38222387-71e12fba-371f-11e8-851f-0eb189cbaa11.png">

<img width="599" alt="screen shot 2018-04-03 at 9 17 04 am" src="https://user-images.githubusercontent.com/11865/38222462-d4de3806-371f-11e8-8038-2dac9d91b90a.png">

**Comment by opoudjis** [comment]
1. No em-dash in Chinese title; removed spaces in English title.
2. This was not a spacing issue, but a Liquid template whitespace issue. (Of course, so long as the identicality clause is in SimSun, it will look like there's extra space after the comma anyway.)
3. No em-dash in Chinese title.
4. Fixed.
