### ISSUE TITLE
Cover page styling: recreating the issuer names in the footer

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#66]
I've discovered how to faithfully recreated it in text -- in original documents they were always an image.

First column:
* Font: FZXiaoBiaoSong-B05
* Font size: 19pt
* Font style: normal (non-bold)
* Length: 4.7"
* Character width: 88% (called character spacing) 
* “Fit to width” / Spread to width

Third column:
* Font: SimHei
* Font size: 14pt
* Font style: Bold
* Length: 0.5"
* “Fit to width” / Spread to width

Note: the only issue is the vertical spacing between two cells in the first column.

Recreated:

中华人民共和国国家质量监督检验检疫总局 |   | 发布
-- | -- | --
中国国家标准化管理委员会 |  

<img width="718" alt="screen shot 2018-04-03 at 12 28 37 pm" src="https://user-images.githubusercontent.com/11865/38227711-90674a58-373a-11e8-870f-359953613729.png">

Original:
![sac](https://user-images.githubusercontent.com/11865/38227670-5bbb0754-373a-11e8-9e00-bae7b1fcce56.png)

See attached Word doc for actual specs.
[testing-of-issuer-layout-independent.docx](https://github.com/riboseinc/asciidoctor-gb/files/1870096/testing-of-issuer-layout-independent.docx)

**Comment by opoudjis** [comment]
This has to work for all issuers, not just one. Is FZXiaoBiaoSong-B05 a common font? We might need to go image for this issuer anyway, since this one is the problematic one.

**Comment by opoudjis** [comment]
I will still generate a table for multi-row issuers, just in case, but for the GB issuer, I will use svg instead.

**Comment by opoudjis** [comment]
Because the format is [5mm blank]发[3mm blank]布 (!), I will be using a table for all issuers anyway, to enforce that separation.

**Comment by ronaldtse** [comment]
Default GB issuer logo uploaded to https://github.com/riboseinc/gbdoc/commit/9f32c9fbfa90435f8ed718af677294ebf9a6bd29

**Comment by opoudjis** [comment]
Logo used.
