### ISSUE TITLE
Terms and definitions: styling of source and modification

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#67]
Two types of sources, direct import or import and modified.

Right now it looks like this:
* direct import: "【GB/T 22080-2008, 改写 — 3.3】"
* modified: "【GB/T 22080-2008, 改写 — 3.2, The term "cargo rice" is shown as deprecated, and Note 1 to entry is not included here】"

According to GB/T 1.1, it should look like this:

* direct import: 
<img width="649" alt="screen shot 2018-04-05 at 10 12 07 am" src="https://user-images.githubusercontent.com/11865/38342542-fbaeee94-38b9-11e8-9249-a435e4cc7d8a.png">

Text: " 【GB/T 200001—2002，定义2.3.5】"
("定义" means "Definition")

* modified:

<img width="649" alt="screen shot 2018-04-05 at 10 12 11 am" src="https://user-images.githubusercontent.com/11865/38342543-003e2150-38ba-11e8-9ed3-6d7474d39a2f.png">

In the "modified" form, it is transformed into a "Note" rather than in the bracket form.

Text: "注：改写GB/T 200001—2002，定义2.10.1"
("注" means "Note", "改写" means "modify", "定义" means "definition")

**Comment by opoudjis** [comment]
So we're reverting to the GB/T 1.1 way of doing this, rather than enforcing ISO/IEC DIR 2.
