### ISSUE TITLE
Remove document attribute `doctype` from asciidoctor-gb

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#71]
The IsoDoc `doctype` attribute is superseded by the GB combination of:

> :scope:
> The scope of the GB standard (national, sector, professional, local, enterprise). Defaults to national.

> :mandate:
> The mandate of the GB standard (mandatory, recommended, guidelines). Defaults to mandatory.

It is currently inherited from asciidoctor-iso, but we should remove the `doctype` attribute from asciidoctor-gb.

**Comment by opoudjis** [comment]
I disagree that doctype is overridden by scope + mandate; I think it is only mandate. 

Cf in ISO:

````
BibItemType |=
     "international-standard" | "technical-specification" |
     "technical-report" | "publicly-available-specification" |
    "international-workshop-agreement" | "guide"
````

And in CSD:

````
BibItemType |= "governance" | "standard" | "guide"
````

I don't see why we need 5*3 types, when we're already encoding scope anyway; only mandate is comparable to the other standards.

**Comment by ronaldtse** [comment]
I'm not suggesting we do 5*3 types -- I'm saying that we already have mandate and scope so we don't need doctype anymore.

Are you proposing we re-purpose the ISO BibItemType terms when used with GB for GB mandate like this mapping?

ISO | GB
-- | --
"international-standard" => "standard" | "standard"
"guide" | "guidelines"
?? | "recommendation"

1. Semantically both GB, GB/T prefixes designate "standards" though.
2. What is "??" then?

**Comment by opoudjis** [comment]
Well, that's what I thought you wanted, and that would make "recommendation" a new standard type. But if you're ok to stick with "standard" and "guide", that's fine by me.

**Comment by opoudjis** [comment]
No, the wording "international standard" is prescribed by ISO, so we should not change it there.
