### ISSUE TITLE
Renaming "activation date" to "implementation date"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#75]
I noticed on SAC's (China's National Body) they use the term "Implementation Date" instead of "Activation Date". Is it difficult for us to re-name this (model, implementation)?

**Comment by opoudjis** [comment]
Not difficult, no.

**Comment by ronaldtse** [comment]
That was just *speed*.

**Comment by opoudjis** [comment]
... I am spoiling you... :-|

**Comment by ronaldtse** [comment]
😜
