### ISSUE TITLE
Citation for "All Parts" rendered in English even when text is Hans

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#77]
This is generated from https://github.com/riboseinc/gmt-0009-2012/blob/master/index-zh.adoc

<img width="453" alt="screen shot 2018-04-18 at 12 11 29 am" src="https://user-images.githubusercontent.com/11865/38882598-20639bb2-429d-11e8-97b9-ae645185f00c.png">

It should be “GM/T 0003（所有部分）” instead.

**Comment by opoudjis** [comment]
Fixed in isodoc.
