### ISSUE TITLE
Resolve title page substitutions

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-gb#8]
Refer https://github.com/riboseinc/gbdoc/issues/4

**Comment by opoudjis** [comment]
Done published date and activated date; need feedback on the rest of the fields.

**Comment by opoudjis** [comment]
* Parameterise the library codes, https://github.com/riboseinc/gbdoc/issues/4 (1)
* Get the publisher and codes (2,3,7) from https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-sector-prefix.adoc

> All text elements are included in the GBDoc repo (the adoc files in models/). Only the “GB” graphical element is in GBDoc (or asciidoctor-gb), I will get the rest prepared when I can.

**Comment by opoudjis** [comment]
> For the top right hand graphic, there are only some cases that they use a logo, most cases they use a "larger font" of text. Here you can see the ones I found (gb-logos.zip). The rest just use large font size, e.g. https://github.com/riboseinc/gbdoc/blob/master/reference-docs/AQ%201030-2007.pdf

**Comment by opoudjis** [comment]
Library codes: done.

**Comment by opoudjis** [comment]
Done Standards class and agency for Sector and National standards, and propagated it to title pages. I don't have enough data yet to do local, enterprise, professional standards.

TO DO: logos.

**Comment by opoudjis** [comment]
Logo and alternate text working.

BUT: SVG only works on Windows Office 365; I cannot import it or read it. https://support.office.com/en-us/article/edit-svg-images-in-microsoft-office-2016-69f29d39-194a-4072-8c35-dbe5e7ea528c?ui=en-US&rs=en-US&ad=US&fromAR=1, https://superuser.com/questions/397644/inserting-svg-files-in-a-microsoft-word-document

**Comment by opoudjis** [comment]
https://support.office.com/en-us/article/graphic-file-types-you-can-insert-and-save-dad53574-3384-4ced-b472-348d37c326a7 for what Mac Word currently allows. @ronaldtse, pick a format. TIFF?

**Comment by ronaldtse** [comment]
Provided GB logos in GIF in gbdoc https://github.com/riboseinc/gbdoc/commit/4aacec86e560adb82be768f4756400507402f687

**Comment by opoudjis** [comment]
Guidance on local standards from https://github.com/riboseinc/gbdoc/issues/5. Will leave professional and enterprise standards out.
