### ISSUE TITLE
gbstandard.rng

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/asciidoctor-gb#81]
I can't find schema description for GbDoc Model attributes. Should the attributes be serialized when Gb standard fetched?

**Comment by opoudjis** [comment]
Yes. Because the serialisations for the standards models are so interdependent, I have put them all in https://github.com/riboseinc/metanorma-iso/tree/master/grammars . Note that the GB grammar inherits from ISO, with some overrides.
