### ISSUE TITLE
7 levels of sections needed in GM/T 0015 document

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#90]
This is the issue: https://github.com/riboseinc/gmt-0015-2012/issues/1

Somehow we need to solve it...

**Comment by opoudjis** [comment]
See comment on 
https://github.com/riboseinc/gmt-0015-2012/issues/1. A solution is possible, but will need added coding, and will be vulnerable.

**Comment by opoudjis** [comment]
Done in asciidoctor-iso
