### ISSUE TITLE
T&D section gives out ISO not GB boilerplate (Chinese and English)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-gb#92]
Current gem gives out ISO boilerplate for the T&D section. It should have been the GB boilerplate.

Chinese:
<img width="483" alt="screen shot 2018-07-25 at 9 07 08 pm" src="https://user-images.githubusercontent.com/11865/43219018-cfead8b2-904e-11e8-8250-ea791090cfe6.png">

English:
<img width="814" alt="screen shot 2018-07-25 at 9 07 12 pm" src="https://user-images.githubusercontent.com/11865/43219026-d2afdcc8-904e-11e8-8991-48cb6ce07c7e.png">

**Comment by opoudjis** [comment]
I don't believe I've ever seen GB-specific boilerplate, and there certainly isn't any in the code or YAML configuration. We assumed it would be user supplied, and present or ignored via a document attribute. If there is known GB boilerplate for T&D, please supply it in Chinese and English.

**Comment by ronaldtse** [comment]
Yes we had that conversation, boilerplate located here: https://github.com/riboseinc/asciidoctor-gb/issues/23#issuecomment-367169593

**Comment by opoudjis** [comment]
Right, so the only thing from ISO that needs to be suppressed is `term_def_boilerplate`: 

````
      <p>ISO和IEC用于标准化的术语数据库地址如下：</p>
      <ul>
      <li> <p>ISO在线浏览平台:
        位于<a href=http://www.iso.org/obp>http://www.iso.org/obp</a></p> </li>
      <li> <p>IEC Electropedia:
        位于<a href=http://www.electropedia.org>http://www.electropedia.org</a>
      </p> </li> </ul>
````

**Comment by opoudjis** [comment]
The current logic there is that the ISO boilerplate is added if there isn't any boilerplate supplied by the user. That must be a misunderstanding: the ISO boilerplate is not to be supplied regardless of what the user has typed. 

What should be supplied, presumably, only if there isn't any boilerplate supplied by the user is the content before that, 本文件不提供术语和定义 or 下列术语和定义适用于本文件 or %界定的术语和定义适用于本文件 or % 界定的以及下列术语和定义适用于本文件. Please confirm.

**Comment by ronaldtse** [comment]
Yes. Correct. The first one is when there are no terms; the second only terms provided below, the third when terms are purely sourced from external sources, the last one when terms sourced and are also provided in this document.
